const cursoinfo = {
    'Análise e Desenvolvimento de Sistemas': 'O tecnólogo em Análise e Desenvolvimento de Sistemas analisa, projeta, documenta, especifica, testa, implanta e mantém sistemas computacionais de informação. Esse profissional trabalha, também, com ferramentas computacionais, equipamentos de informática e metodologia de projetos na produção de sistemas. Raciocínio lógico, emprego de linguagens de programação e de metodologias de construção de projetos, preocupação com a qualidade, usabilidade, robustez, integridade e segurança de programas computacionais são fundamentais à atuação desse profissional.',
    'Eletrônica Automotiva': 'O tecnólogo em Eletrônica Automotiva atua no desenvolvimento de novos produtos e tecnologias na área automotiva, além de supervisionar, coordenar e orientar equipes envolvidas em diversas atividades, como a padronização e controle de qualidade em veículos especiais, de carga e passeio. Ele é responsável pela especificação de instrumentos e equipamentos para teste, oferecendo consultoria e assistência técnica, bem como elaborando orçamentos para a indústria automotiva. Também gerencia e realiza vistorias, perícias e avaliações técnicas, e supervisiona equipes em linhas de inspeção veicular. Sua função inclui selecionar e desenvolver novas tecnologias considerando aspectos técnicos, econômicos e gerenciais dos sistemas automobilísticos, operar e manter equipamentos de inspeção veicular, estudar a viabilidade técnico-econômica de oficinas autorizadas ou independentes, e coordenar tecnicamente as equipes dessas oficinas.',
    'Fabricação Mecânica': 'O tecnólogo em Fabricação Mecânica atua no segmento de fabricação, envolvendo usinagem, conformação, soldagem, montagem e outros processos mecânicos. Planeja, controla e gerencia os diversos processos, atuando no desenvolvimento e melhoria de produtos, dos processos de fabricação e na gestão de projetos, aliando competências das áreas de gestão, qualidade e controle ambiental. Exerce suas atividades em empresas do ramo metal-mecânico, incluindo indústrias manufatureiras e ferramentarias, podendo ainda atuar em institutos e centros de pesquisa, órgãos governamentais, escritórios de consultoria, dentre outros.',
    'Gestão Empresarial EAD': 'O Tecnólogo em Gestão Empresarial elabora e implementa planos de negócios, utilizando métodos e técnicas de gestão na formação e organização empresarial especificamente nos processos de comercialização, suprimento, armazenamento, movimentação de materiais e no gerenciamento de recursos financeiros e humanos. A habilidade para lidar com pessoas, capacidade de comunicação, trabalho em equipe, liderança, negociação, busca de informações, tomada de decisão em contextos econômicos, políticos, culturais e sociais distintos, são requisitos importantes a esse profissional.',
    'Gestão da Qualidade': 'O Tecnólogo em Gestão da Qualidade será um profissional que planeja, implementa e audita sistemas de gestão da qualidade e produtividade. Realiza mapeamento de processos organizacionais segundo indicadores de qualidade e produtividade. Elabora e analisa documentação e relatórios de qualidade, considerando normas de qualidade estabelecidas. Desenvolve avaliação sistemática dos procedimentos, práticas e rotinas internas e externas de uma organização. Mobiliza pessoas para agir com qualidade em todas as atividades corporativas. Gerencia e mantém o fluxo de informação e comunicação na empresa. Dissemina a cultura da qualidade e produtividade. Capacita pessoas em procedimentos e rotinas destinados a minimizar a produção fora de conformidade (utilizando softwares específicos). Elabora ferramentas para minimizar a incidência de falhas. Através da análise de dados (Estatística), Six Sigma, conduz programas de melhorias na Qualidade da empresa. Elabora e gerencia estratégias para obtenção de certificações, garantia e auditoria da Qualidade. Desenvolve programa de avaliação de performance produtiva organizacional considerando aspectos quantitativos e qualitativos. Avalia e emite parecer técnico em sua área de formação.',
    'Manufatura Avançada': 'O aluno do curso aprende a transformar ambientes de manufatura convencional em contextos mais tecnológicos, sendo capacitado através de blocos temáticos focados em projetos. O conteúdo abrange processos de manufatura, eletrônica e automação, bem como áreas multidisciplinares. A formação inclui uma base em desenho técnico, matemática para cálculos de projetos e gestão de carreira, além de inglês técnico. Já o profissional formado atua como integrador de tecnologia, projetando e desenvolvendo soluções para a manufatura, e incorporando novas tecnologias associadas à Indústria 4.0. Ele oferece informações sobre técnicas de produção modernas, como materiais e processos de fabricação, realidade aumentada e virtual, Internet das Coisas e Big Data. Além de identificar e utilizar dispositivos e ferramentas disponíveis no mercado, o profissional pode empreender ao abrir sua própria consultoria ou empresa, ou se envolver em pesquisas.',
    'Logística': 'O tecnólogo em Logística é o profissional especializado em armazenagem, distribuição e transporte. Atuando na área logística de uma empresa, planeja e coordena a movimentação física e de informações sobre as operações multimodais de transporte, para proporcionar fluxo otimizado e de qualidade para peças, matérias-primas e produtos. Ele gerencia redes de distribuição e unidades logísticas, estabelecendo processos de compras, identificando fornecedores, negociando e estabelecendo padrões de recebimento, armazenamento, movimentação e embalagem de materiais, podendo ainda ocupar-se do inventário de estoques, sistemas de abastecimento, programação e monitoramento do fluxo de pedidos.',
    'Polímeros': 'Esse profissional trabalha na fabricação dos Polímeros, compostos químicos utilizados na fabricação de produtos como o plástico, por exemplo. Avalia o desempenho de equipamentos e processos, interpreta fluxogramas de processos, aplica formulação química de polímeros, tintas e vernizes e desenvolve métodos de análises laboratoriais para caracterização dos materiais poliméricos, além de processos de modelagem. O monitoramento da qualidade e dos processos de reciclagem envolvidos; a identificação e acompanhamento das variáveis relevantes, inclusive as referentes ao meio ambiente, são também funções desse profissional.',
    'Processos Metalúrgicos': 'O tecnólogo em Processos Metalúrgicos utiliza os fenômenos envolvidos em processos como: tratamentos térmicos, fundição, siderurgia, laminação, forjamento de metais, sinterização e tratamentos de superfície .São atividades inerentes aos egressos deste Curso o planejamento, gestão, controle dos processos e comercialização dos produtos metalúrgicos, através da seleção, dimensionamento de equipamentos e métodos de fabricação. Incluem-se as atividades de laboratórios de ensaios mecânicos e de ensaios metalográficos, com o domínio da interrelação entre microestrutura, propriedades e aplicações dos produtos metálicos. Este profissional possui competências de gestão ambiental, de pessoas e processos industriais. Pode atuar em diversas empresas do ramo metal-mecânico e ainda no ensino superior.',
    'Projetos Mecânicos': 'O tecnólogo em Projetos Mecânicos está habilitado a realizar projetos, com detalhamento técnico de sistemas mecânicos que envolvam máquinas, motores, instalações mecânicas e termo-mecânicas. Tem conhecimento de todos os materiais usuais em construção mecânica e suas aplicações práticas. Está capacitado a atuar na área de organização industrial mecânica, tanto para processos como para produtos industriais. Domina a técnica do projeto de dispositivos e ferramentas de produção mecânica. Pode dedicar-se ao ensino, à pesquisa tecnológica, bem como realizar vistoria, avaliação e laudo técnico, em seu campo profissional.',
    'Sistemas Biomédicos': 'O tecnólogo em Sistemas Biomédicos é responsável por planejar, gerenciar, implantar e manter equipamentos clínicos e médico-hospitalares. Supervisiona e coordena equipes de manutenção e otimização do uso de equipamentos eletro-médicos. Assessora a aquisição, executa a instalação, capacita usuários de equipamentos e sistemas biomédicos, além de participar de equipes de pesquisa aplicada. Responsável também pela implantação e controle das normas de segurança dos equipamentosnos serviços de saúde, pode atuar em hospitais, policlínicas, laboratórios, fabricantes e distribuidoras de equipamentos hospitalares.'

}
function verify() {
    const select = document.getElementById('opcoes')
    const selectvalue = select.value

    if (selectvalue !== '') {
        var confirmacao = confirm(`Deseja saber mais sobre o curso?`)

        if (confirmacao) {
            const altura = 300
            const largura = 600
            const janela = window.open('', 'Curso', `width=${largura},height=${altura}`)

            janela.document.write(`
                <html>
                <head><title>Informações do Curso - ${selectvalue}</title></head>
                <body>
                    <h1>Curso de ${selectvalue}</h1>
                    <p>${cursoinfo[selectvalue]}</p>
                </body>
                </html>`)
        }
    }
}